# Tests the systemd-openbaod fileSecrets provider end-to-end.
#
# Sets up:
# - OpenBao server in dev mode (no TLS, root token "root")
# - vault-agent with token auth, rendering secrets to files
# - systemd-openbaod provider fulfilling a fileSecrets contract
#
# Verifies that the secret content, ownership, and permissions are correct.
{ lib, pkgs, ... }:
let
  secretContent = "super-secret-from-openbao";
  secretOwner = "testuser";
  secretGroup = "testgroup";
  secretMode = "0440";
in
{
  name = "contracts-systemd-openbaod";

  nodes.machine =
    { config, pkgs, ... }:
    {
      virtualisation.memorySize = 1024;

      # OpenBao dev server - runs without init/unseal, no TLS.
      systemd.services.openbao-dev = {
        description = "OpenBao Dev Server";
        wantedBy = [ "multi-user.target" ];
        after = [ "network.target" ];
        environment = {
          BAO_DEV_ROOT_TOKEN_ID = "root";
          BAO_DEV_LISTEN_ADDRESS = "127.0.0.1:8200";
          HOME = "/tmp";
        };
        path = [
          pkgs.bash
          pkgs.coreutils
        ];
        serviceConfig = {
          ExecStart = "${pkgs.openbao}/bin/bao server -dev";
          Restart = "on-failure";
          LimitMEMLOCK = "infinity";
        };
      };

      environment.variables = {
        BAO_ADDR = "http://127.0.0.1:8200";
        BAO_TOKEN = "root";
      };

      # vault-agent instance for systemd-openbaod, authenticating with token.
      # Start after openbao-dev to avoid connection-refused backoff storms.
      systemd.services.vault-agent-systemd-openbaod.after = [ "openbao-dev.service" ];
      services.vault-agent.instances.systemd-openbaod = {
        enable = true;
        package = pkgs.openbao;
        settings = {
          vault.address = "http://127.0.0.1:8200";
          auto_auth = [
            {
              method = [
                {
                  type = "token_file";
                  config.token_file_path = pkgs.writeText "vault-token" "root";
                }
              ];
            }
          ];
          # templates are generated by the systemd-openbaod module
        };
      };

      # Enable the systemd-openbaod provider.
      services.systemd-openbaod.enable = true;

      # Consumer requests a secret via the fileSecrets contract.
      contracts.fileSecrets = {
        want.consumer.mySecret = {
          request = {
            owner = secretOwner;
            group = secretGroup;
            mode = secretMode;
          };
        };
        defaultProviderName = "systemd-openbaod";
      };

      # Provider-specific config: where in OpenBao to find the secret.
      services.systemd-openbaod.fileSecrets.consumer.mySecret.openbaoPath = "secret/data/test";

      # hardcoded-secret is in the module list and auto-consumes all requests;
      # provide a dummy content so it doesn't error.
      testing.hardcoded-secret.fileSecrets.consumer.mySecret.content = "placeholder";

      # Create the user/group that owns the secret.
      users.users.${secretOwner} = {
        isNormalUser = true;
        group = secretGroup;
      };
      users.groups.${secretGroup} = { };

      environment.systemPackages = [ pkgs.openbao ];
    };

  testScript =
    { nodes, ... }:
    let
      secretPath = nodes.machine.contracts.fileSecrets.results.consumer.mySecret.path;
    in
    ''
      machine.wait_for_unit("openbao-dev.service")
      machine.wait_for_open_port(8200)

      # Wait for the dev server to be fully ready, then seed a secret.
      machine.wait_until_succeeds(
          "bao kv put secret/test value='${secretContent}'"
      )

      # Wait for vault-agent to render the secret file.
      machine.wait_for_unit("vault-agent-systemd-openbaod.service")
      machine.wait_for_file("${secretPath}")

      # Verify content.
      content = machine.succeed("cat ${secretPath}").strip()
      assert content == "${secretContent}", \
          f"Expected '${secretContent}', got '{content}'"

      # Verify ownership (set by activation script).
      owner = machine.succeed("stat -c '%U' ${secretPath}").strip()
      assert owner == "${secretOwner}", \
          f"Expected owner '${secretOwner}', got '{owner}'"

      group = machine.succeed("stat -c '%G' ${secretPath}").strip()
      assert group == "${secretGroup}", \
          f"Expected group '${secretGroup}', got '{group}'"

      # Verify permissions (set by vault-agent template).
      mode = str(int(machine.succeed("stat -c '%a' ${secretPath}").strip()))
      expected_mode = str(int("${secretMode}"))
      assert mode == expected_mode, \
          f"Expected mode '{expected_mode}', got '{mode}'"
    '';

  meta.maintainers = with lib.maintainers; [ kiara ];
}
